SalesForce/Assignment_13/src/objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>BillToContact__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>BillToContact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Opportunities</relationshipLabel>
        <relationshipName>Opportunities</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Manager__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Manager</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Opportunities</relationshipLabel>
        <relationshipName>Opportunities</relationshipName>
        <type>Lookup</type>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

SalesForce/Assignment_3/src/classes/OpportunityController.cls
public class OpportunityController {

    public static void populateInOpportunity(List<Opportunity> oppList) {
     
        for(Opportunity opp:oppList){
             System.debug(opp.BillToContact__c);
            System.debug(opp.Manager__c);
            System.debug('ghdshkj');
            if(opp.BillToContact__c != null && opp.Manager__c == null)
            {
                System.debug(opp.AccountId);
                System.debug(opp.BillToContact__c);
                opp.Manager__c =opp.AccountId;
                   System.debug(opp.Manager__c);
            }
            
        }
     
    }
}