SalesForce/Assignment_1/src/objects/Class__c.object
<CustomObject>
    <fields>
        <fullName>Board__c</fullName>
        <label>Board</label>
        <picklist>
            <picklistValues>
                <fullName>RAJ</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>CBSE</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>BIHAR</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Fee__c</fullName>
        <label>Fee</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Currency</type>
    </fields>
    <label>Class</label>
    <nameField>
        <label>Class Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Classes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

SalesForce/Assignment_5/Assignment_5/src/classes/ManageClassController.cls
public with sharing class ManageClassController {
    
    // To Display the Records
    public Class__c recordsToDisplay { get; private set; }
    // To save the Records
    public Class__c saveRecords { get; private set; }
    // To Update the Record
    public String idToUpdate {get;set;}
    // To display the Popup
    public boolean displayPopup {get; set;} 
    
    public String thisClass {get; set;}
    // Query to get the Details
    String query = 'SELECT Id, Name, fee__c, board__c FROM Class__c ';
    // Constructor
    public ManageClassController(ApexPages.StandardController controller) {
        idToUpdate ='';
    }
    
    public void saveDetails() {  
        displayPopup = false;
        update saveRecords;
        
    }  
    
    public void deleteDetails() { 
        saveRecords = [SELECT 
                       id,name,fee__C 
                       FROM
                       Class__c 
                       WHERE id = :idToUpdate];
        delete saveRecords;
    }  
    
    public void ShowDataToEdit() { 
        // Query to fetch the Records
        saveRecords = [SELECT
                       id, name, fee__c,board__C 
                       FROM Class__c 
                       WHERE id = :idToUpdate];
        displayPopup = true;    
    }   
    
    public List<Class__C> getRecords() 
    {
        return Database.query(query);
    }  
}